os: linux
dist: xenial
language: python

python:
  - "3.7"

services: postgresql

addons:
  postgresql: "10"

env:
  DJANGO: "3.0"

install:
  - pip install -r requirements/common.txt

before_script:
  - createdb -U postgres djangoqueries
  - python manage.py migrate --noinput

script:
  - python manage.py test
