os: linux
dist: xenial
language: python

python:
  - "3.7"

services: postgresql

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
  jobs:
  - DJANGO=3.0
  global:
  - PGPASSWORD=travis
  - PGPORT=5433
  - PGUSER=travis

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE djangoqueries;" -U travis
  - psql -c "ALTER USER travis WITH PASSWORD 'travis';" -U travis
  - python manage.py migrate --noinput

script:
  - python manage.py test
