os: linux
dist: xenial
language: python

python:
  - "3.7"

services: postgresql

addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12

env:
  PGPORT: "5433"
  DJANGO: "3.0"

install:
  - pip install -r requirements/common.txt

before_script:
  - createdb -U postgres djangoqueries
  - python manage.py migrate --noinput

script:
  - python manage.py test
