os: linux
dist: xenial
language: python

python:
  - "3.8"

services: postgresql

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

env:
  jobs:
  - DJANGO=3.0
  global:
  - PGPASSWORD=djangoqueries
  - PGPORT=5433
  - PGUSER=djangoqueries

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE USER djangoqueries WITH CREATEDB SUPERUSER PASSWORD 'djangoqueries';" -U travis
  - psql -c "CREATE DATABASE djangoqueries OWNER djangoqueries;" -U travis
  - python manage.py migrate --noinput

script:
  - python manage.py test
