os: linux
dist: focal
language: python

python:
  - "3.8"

services:
  - postgresql

addons:
  postgresql: "12"

env:
  jobs:
  - DJANGO=3.1
  global:
  - PGHOST=
  - PGPASSWORD=
  - PGPORT=
  - PGUSER=

install:
  - pip install -r requirements.txt

before_script:
  - createdb -U postgres djangoqueries
  - python manage.py migrate --noinput

script:
  - python manage.py test
